name: Unit test

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '20 00 1 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1', 'nightly']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - name: "Compat fix for Julia < v1.3.0"
        if: ${{ matrix.julia-version == '1.0' }}
        run: |
          using Pkg
          Pkg.add([
            PackageSpec(name="FFTW", version="1.1"),
            PackageSpec(name="AbstractFFTs", version="0.5")
          ])
        shell: julia --project=. --startup=no --color=yes {0}
      - name: "Unit Test"
        uses: julia-actions/julia-runtest@master

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
