name: Unit test

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
        os: [ubuntu-latest, windows-latest, macOS-13]
        arch: [x64]
        include:
          - os: macOS-latest
            julia-version: '1'
            arch: aarch64
          - os: ubuntu-latest
            julia-version: '1'
            arch: x86
          - os: ubuntu-latest
            julia-version: 'min'
            arch: x64
          - os: ubuntu-latest
            julia-version: 'nightly'
            arch: x64

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: Cache artifacts
        uses: julia-actions/cache@v2

      - name: "Unit Test"
        uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
